const apiList = [
    {
        attr:'type',
        desc:'设置input类型，可选值为text number或者不设',
        type:'string',
        default:'text'
    },
    {
        attr:'digits',
        desc:'设置input的个数',
        type:'number',
        default:'6'
    },
    {
        attr:'focus',
        desc:'input是否触发焦点',
        type:'boolean',
        default:'false'
    },
    {
        attr:'popupKeyboard',
        desc:'是否弹出自定义数字键盘',
        type:'boolean',
        default:'false'
    },
    {
        attr:'autoSubmit',
        desc:'是否填写完成自动提交',
        type:'boolean',
        default:'false'
    },
    {
        attr:'callback',
        desc:'用于接收填写内容的callback方法或自动提交的callback',
        type:'function',
        default:'null'
    },
]
export default apiList;